# Place in: anomek/MyDalamudPlugins -> generate_pluginmaster.py
# Originally based on https://github.com/Aireil/MyDalamudPlugins/blob/master/generate_pluginmaster.py
# Reworked to build download links from GitHub Releases (counted) instead of committed raw zips.

import json
import os
import re
import urllib.request
import urllib.error
from datetime import datetime, timezone
from time import time

TOKEN = os.environ.get('GITHUB_TOKEN', '')

RELEASE_ASSET = 'latest.zip'
# Stable URL that always redirects to the newest release's asset.
DOWNLOAD_URL = 'https://github.com/{owner}/{repo}/releases/latest/download/' + RELEASE_ASSET

DEFAULTS = {
    'IsHide': False,
    'IsTestingExclusive': False,
    'ApplicableVersion': 'any',
}

DUPLICATES = {
    'DownloadLinkInstall': ['DownloadLinkTesting', 'DownloadLinkUpdate'],
}

TRIMMED_KEYS = [
    'Author',
    'Name',
    'Punchline',
    'Description',
    'Changelog',
    'InternalName',
    'AssemblyVersion',
    'RepoUrl',
    'ApplicableVersion',
    'Tags',
    'DalamudApiLevel',
    'IconUrl',
    'ImageUrls',
]

BADGE_START = '<!-- DOWNLOADS:START (generated by generate_pluginmaster.py - do not edit) -->'
BADGE_END = '<!-- DOWNLOADS:END -->'


def main():
    manifests = load_manifests()
    master = [trim_manifest(m) for m in manifests]
    add_extra_fields(master)
    write_master(master)
    write_readme_badges(master)


def load_manifests():
    manifests = []
    for name in sorted(os.listdir('plugins')):
        path = os.path.join('plugins', name, f'{name}.json')
        if not os.path.isfile(path):
            continue
        with open(path, encoding='utf-8') as f:
            manifests.append(json.load(f))
    return manifests


def trim_manifest(plugin):
    return {k: plugin[k] for k in TRIMMED_KEYS if k in plugin}


def parse_repo(repo_url):
    m = re.search(r'github\.com[:/]+([^/]+)/([^/]+?)(?:\.git)?/?$', (repo_url or '').strip())
    if not m:
        return None, None
    return m.group(1), m.group(2)


def api_get(url):
    req = urllib.request.Request(url)
    req.add_header('Accept', 'application/vnd.github+json')
    req.add_header('X-GitHub-Api-Version', '2022-11-28')
    if TOKEN:
        req.add_header('Authorization', f'Bearer {TOKEN}')
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode('utf-8'))


def fetch_releases(owner, repo):
    releases, page = [], 1
    while True:
        try:
            batch = api_get(
                f'https://api.github.com/repos/{owner}/{repo}/releases?per_page=100&page={page}'
            )
        except urllib.error.HTTPError as e:
            print(f'  ! releases fetch failed for {owner}/{repo}: {e}')
            break
        if not batch:
            break
        releases.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return releases


def release_stats(owner, repo):
    """Returns (download_count, last_update_epoch).
    download_count = MAX asset count across releases (not sum): with auto-update every
    version re-downloads the whole active base, so the peak single release ~= real users."""
    max_count, last_update = 0, 0
    for rel in fetch_releases(owner, repo):
        for asset in rel.get('assets', []):
            if asset.get('name') == RELEASE_ASSET:
                max_count = max(max_count, int(asset.get('download_count', 0)))
        published = rel.get('published_at')
        if published:
            try:
                ts = int(datetime.strptime(published, '%Y-%m-%dT%H:%M:%SZ')
                         .replace(tzinfo=timezone.utc).timestamp())
                last_update = max(last_update, ts)
            except ValueError:
                pass
    return max_count, last_update


def add_extra_fields(manifests):
    for manifest in manifests:
        owner, repo = parse_repo(manifest.get('RepoUrl'))
        if owner and repo:
            manifest['DownloadLinkInstall'] = DOWNLOAD_URL.format(owner=owner, repo=repo)
            count, last_update = release_stats(owner, repo)
            print(f'{manifest.get("InternalName")}: max downloads={count}')
        else:
            count, last_update = 0, 0
            print(f'{manifest.get("InternalName")}: could not parse RepoUrl, skipping releases')

        for k, v in DEFAULTS.items():
            manifest.setdefault(k, v)
        for source, keys in DUPLICATES.items():
            if source not in manifest:
                continue
            for k in keys:
                manifest.setdefault(k, manifest[source])

        manifest['DownloadCount'] = count
        manifest['LastUpdate'] = str(last_update or int(time()))


def write_master(master):
    with open('pluginmaster.json', 'w', encoding='utf-8') as f:
        json.dump(master, f, indent=4)
        f.write('\n')


def write_readme_badges(master):
    if not os.path.isfile('README.md'):
        return
    rows = ['### Downloads', '']
    for m in master:
        count = m.get('DownloadCount', 0)
        badge = f'https://img.shields.io/badge/downloads-{count}-blue'
        rows.append(f'- [{m["Name"]}]({m.get("RepoUrl", "")}) ![downloads]({badge})')
    block = BADGE_START + '\n' + '\n'.join(rows) + '\n' + BADGE_END

    with open('README.md', encoding='utf-8') as f:
        readme = f.read()
    if BADGE_START in readme and BADGE_END in readme:
        readme = re.sub(
            re.escape(BADGE_START) + r'.*?' + re.escape(BADGE_END),
            lambda _: block, readme, flags=re.DOTALL,
        )
    else:
        readme = readme.rstrip() + '\n\n' + block + '\n'
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(readme)


if __name__ == '__main__':
    main()
